version: "3.9"
services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
     - "6379:6379"
    networks:
      - app-net
  myapp_postgres:
    container_name: myapp_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - myappdb-data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:

  myappdb-data:


networks:
  app-net:
    driver: bridge
